import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "render_mermaid.py"
SAFETY_MESSAGE = "must be an independent directory outside the book and protected roots"


class RenderMermaidSafetyTests(unittest.TestCase):
    def make_book(self, parent: Path) -> tuple[Path, Path]:
        book = parent / "book"
        book.mkdir()
        marker = book / "source-marker.txt"
        marker.write_text("preserve me", encoding="utf-8")
        (book / "SUMMARY.md").write_text("# Summary\n", encoding="utf-8")
        return book, marker

    def run_renderer(self, book: Path, output: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                "python3",
                str(SCRIPT),
                "--book-dir",
                str(book),
                "--svg-out",
                str(output),
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )

    def test_rejects_output_equal_to_ancestor_or_inside_book_without_deleting_source(self):
        for relation in ("equal", "ancestor", "inside"):
            with self.subTest(relation=relation), tempfile.TemporaryDirectory() as tmp:
                temp = Path(tmp)
                book, marker = self.make_book(temp)
                if relation == "equal":
                    output = book
                elif relation == "ancestor":
                    output = temp
                else:
                    output = book / "generated"

                result = self.run_renderer(book, output)

                self.assertNotEqual(result.returncode, 0)
                self.assertTrue(marker.is_file(), f"source was deleted for {relation}")
                self.assertIn(SAFETY_MESSAGE, result.stderr)

    def test_rejects_resolved_filesystem_home_and_repository_roots(self):
        protected = (Path("/"), Path.home(), ROOT)
        for target in protected:
            with self.subTest(target=target), tempfile.TemporaryDirectory() as tmp:
                temp = Path(tmp)
                book, marker = self.make_book(temp)
                link = temp / "protected-output"
                link.symlink_to(target, target_is_directory=True)

                result = self.run_renderer(book, link)

                self.assertNotEqual(result.returncode, 0)
                self.assertTrue(marker.is_file())
                self.assertIn(SAFETY_MESSAGE, result.stderr)

    def test_allows_an_independent_output_directory(self):
        with tempfile.TemporaryDirectory() as tmp:
            temp = Path(tmp)
            book, marker = self.make_book(temp)
            output = temp / "output"

            result = self.run_renderer(book, output)

            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertTrue(marker.is_file())
            self.assertTrue(output.is_dir())

    def test_preserves_unrelated_files_in_an_existing_safe_output_directory(self):
        with tempfile.TemporaryDirectory() as tmp:
            temp = Path(tmp)
            book, marker = self.make_book(temp)
            output = temp / "output"
            output.mkdir()
            unrelated = output / "preserve-me.txt"
            unrelated.write_text("not generated by this tool", encoding="utf-8")

            result = self.run_renderer(book, output)

            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertTrue(marker.is_file())
            self.assertTrue(unrelated.is_file())
            self.assertEqual(
                unrelated.read_text(encoding="utf-8"), "not generated by this tool"
            )


if __name__ == "__main__":
    unittest.main()
